Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2018-12, with the labels that each got.

#100 Make the Transceiver's machine field private
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
Labels: bug, minor

#70 Db schema change
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/TransceiverInterface.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadMemoryProcess.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DirectDataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/RecordingRegionDataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/BufferedReceivingData.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/SQLiteConnectionManager.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/SQLiteStorage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/Storage.java
  SpiNNaker-storage/src/main/resources/db.sql
  SpiNNaker-storage/src/test/java/uk/ac/manchester/spinnaker/storage/TestSQLiteStorage.java
Labels: Incomplete, enhancement

#109 Rewrapped line, now that wrapping rules can do it automatically
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
Labels: minor

#110 Use machine defaults constants to clamp range of route bits
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RoutingEntry.java
Labels: bug

#107 Stop ignoring the ignored
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
Labels: bug, minor

#198 fixed hash call on interface
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/SpiNNakerTriadGeometry.java
Labels: bug

#197 More fixing
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/AbstractIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/BaseIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/ChipMemoryIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/Constants.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/FileIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/MemoryIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Constants.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/BootDataBlock.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/BootMessages.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/EIEIODataMessage.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/EIEIOType.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/ChipSummaryInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/DiagnosticFilter.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/MemoryAllocationFailedException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/RouterDiagnostics.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/UnexpectedResponseCodeException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SDRAMAlloc.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocClient.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/exceptions/SpallocProtocolException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/exceptions/SpallocProtocolTimeoutException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/exceptions/SpallocServerException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobMachineInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobsChangedNotification.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/TransceiverInterface.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/UDPTransceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetMachineProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetMulticastRoutesProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadMemoryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/SendSingleBMPCommandProcess.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/DataSpecificationException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/ExecuteBreakInstruction.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/NoMoreException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/NoRegionSelectedException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/RegionInUseException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/RegionNotAllocatedException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/RegionUnfilledException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/UnimplementedDSECommandException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/UnknownTypeLengthException.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Router.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestChip.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestVirtualMachine.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/DefaultMap.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/InetFactory.java
  SpiNNaker-utils/src/test/java/uk/ac/manchester/spinnaker/utils/TestDefaultMap.java
  SpiNNaker-utils/src/test/java/uk/ac/manchester/spinnaker/utils/progress/TestBar.java
  SpiNNaker-utils/src/test/java/uk/ac/manchester/spinnaker/utils/progress/TestIterable.java
Labels: bug, minor

#199 removed mutibility.
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RoutingEntry.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestRoutingEntry.java
Labels: enhancement

#196 Ide gripes
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/ChipLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/CoreSubsets.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/HasCoreLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Link.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineDefaults.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineVersion.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Processor.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Router.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RoutingEntry.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/SpiNNakerTriadGeometry.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/VirtualMachine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/MachineBean.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/InetIdTuple.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/reports/Reports.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/IPTag.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/TrafficIdentifier.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestVirtualMachine.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestMachineBean.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/tags/TestIPTag.java
  SpiNNaker-machine/src/test/resources/test24_12.json
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/ReaderLineIterable.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/TripleMapIterator.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/UnitConstants.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/progress/ProgressBar.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/progress/ProgressIterable.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/progress/ProgressIterator.java
Labels: minor

#209 DSE exec
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Constants.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/HostExecuteDataSpecification.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/DataSpecificationException.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/CommandLineInterface.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/HostExecuteDataSpecification.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/package-info.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/DSEStorage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQL.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteStorage.java
  SpiNNaker-storage/src/main/resources/dse.sql
Labels: enhancement

#214 Control over the logging level
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/LogControl.java
  SpiNNaker-front-end/src/main/resources/log4j.properties
Labels: enhancement, minor
