Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2018-11, with the labels that each got.

#59 Allow storage to take input data as byte buffers.
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/Storage.java
  SpiNNaker-storage/src/test/java/uk/ac/manchester/spinnaker/storage/TestSQLiteStorage.java
Labels: enhancement, minor

#60 Fix two faults in large memory reads
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Constants.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadMemoryProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/ReliabilityITCase.java
Labels: bug

#61 Corrected computation of transfer units and transfer size clamp
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Constants.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/ReadLink.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/ReadMemory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/TransferUnit.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/connections/TestUDPConnection.java
Labels: bug

#65 Allow memory reads to funnel straight to the database
  SpiNNaker-comms/pom.xml
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/TransceiverInterface.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadMemoryProcess.java
Labels: enhancement

#64 Convert board versions to instances of MachineVersion
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/BootMessages.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/SystemVariableBootValues.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/test/java/testconfig/BoardTestConfiguration.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/boot/TestMessage.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/ReliabilityITCase.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/SpallocMachineTest.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineVersion.java
Labels: enhancement

#66 Rename Process.Exception to ProcessException
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/ConnectionListener.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/AbstractIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/ChipMemoryIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/MemoryIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/TransceiverInterface.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ApplicationRunProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/DeallocSDRAMProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/FillProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetCPUInfoProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetHeapProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetMachineProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetMulticastRoutesProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetTagsProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/GetVersionProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/LoadFixedRouteEntryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/LoadMulticastRoutesProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/MallocSDRAMProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/Process.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ProcessException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadFixedRouteEntryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadIOBufProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadMemoryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/ReadRouterDiagnosticsProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/SendSingleBMPCommandProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/SendSingleSCPCommandProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/WriteMemoryFloodProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/WriteMemoryProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/ReliabilityITCase.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/HostExecuteDataSpecification.java
Labels: bug

#67 Extractor
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/WriteFPGARegister.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/CommandLineInterface.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DataReceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DataReceiverRunner.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/Placement.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/Vertex.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/package-info.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/BufferedReceivingData.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/BufferingOperation.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/ChannelBufferState.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/package-info.java
  SpiNNaker-front-end/src/test/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/TestPlacements.java
  SpiNNaker-front-end/src/test/resources/placement.json
  SpiNNaker-front-end/src/test/resources/simple.json
  SpiNNaker-front-end/src/test/resources/vertex.json
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineDefaults.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RegionLocation.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestRegionLocation.java
Labels: enhancement

#72 constants cleanup
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/Listenable.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/Constants.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/SetPower.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/BootMessages.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobDescription.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/SendSingleBMPCommandProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/ManualSpalloc.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/UnitConstants.java
Labels: enhancement

#94 Indentation in checkstyle
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/SystemVariableBootValues.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/HostDataRead.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/SpinnakerRequestReadData.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/ChipInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DataReceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/storage_objects/BufferedReceivingData.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Direction.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineVersion.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Processor.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RoutingEntry.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/ReaderLineIterable.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/progress/ProgressBar.java
  pom.xml
  src/support/checkstyle/style.xml
Labels: enhancement

#97 Minor fixes
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Functions.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/MemoryRegionCollection.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/NoMoreException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/RegionNotAllocatedException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/exceptions/UnimplementedDSECommandException.java
  SpiNNaker-data-specification/src/test/java/uk/ac/manchester/spinnaker/data_spec/Generator.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/CommandLineInterface.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/Constants.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataOut.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/ProtocolMessage.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/DataReceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/interfaces/buffer_management/Vertex.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/ChipInformation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/CoreSubsetsFailedChipsTuple.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineDefaults.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Router.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/SpiNNakerTriadGeometry.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/VirtualMachine.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestChip.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestCoreSubsetsFailedChipTuple.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestMachine.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestVirtualMachine.java
Labels: enhancement
