Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2018-10, with the labels that each got.

#32 Move Reports to better place
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Reports.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/reports/Reports.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/reports/package-info.java
Labels: bug

#31 Data downloader
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/Connection.java
  SpiNNaker-front-end/pom.xml
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/Constants.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataOut.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/HostDataReceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/MissingSequenceNumbersMessage.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/ProtocolID.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/ProtocolMessage.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/StartSendingMessage.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/package-info.java
  pom.xml
Labels: enhancement

#36 Fix broken SCP serialization
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/SCPSender.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/BootMessages.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/VersionInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPResponse.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPResultMessage.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SDPHeader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SpinnakerRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/processes/ReadMemoryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/processes/SendSingleBMPCommandProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/connections/TestUDPConnection.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/TestCountState.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/TestOKResponse.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/TestVersion.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/TestMockClient.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/messages/TestMachine.java
  SpiNNaker-comms/src/test/resources/testconfig/test.cfg
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/Ping.java
Labels: bug

#39 Fix spalloc usage for integration tests
  SpiNNaker-comms/src/test/java/testconfig/BoardTestConfiguration.java
Labels: bug

#35 DSE high level ops
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/CPUInfo.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/TestJob.java
  SpiNNaker-data-specification/pom.xml
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Constants.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Executor.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/HostExecuteDataSpecification.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/MemoryRegion.java
Labels: enhancement

#45 Throttle p2pColumn
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/P2PTable.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/processes/GetMachineProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
Labels: bug

#46 Tag and wraparound
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineVersion.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestChip.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestMachine.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestMachineVersion.java
Labels: bug

#48 Stop reordering
  .travis.yml
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/processes/GetMachineProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/ReliabilityITCase.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TransceiverITCase.java
Labels: bug, critical

#40 DB storage
  SpiNNaker-storage/pom.xml
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/ConnectionProvider.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/DatabaseEngine.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/RemoveMe.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/SQLiteStorage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/Storage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/StorageException.java
  SpiNNaker-storage/src/main/resources/db.sql
  SpiNNaker-storage/src/test/java/.gitignore
  SpiNNaker-storage/src/test/java/uk/ac/manchester/spinnaker/storage/TestSQLiteStorage.java
  SpiNNaker-storage/src/test/resources/log4j.properties
  pom.xml
Labels: enhancement

#55 Command line API
  SpiNNaker-front-end/pom.xml
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/CommandLineInterface.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/package-info.java
  SpiNNaker-front-end/src/main/resources-filtered/command-line.properties
  SpiNNaker-front-end/src/main/resources/log4j.properties
Labels: enhancement

#54 Throw Exception is spalloc is asked for machine info while still queued.
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocJobAPI.java
Labels: bug

#52 Machine json
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/ChipLocationBean.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/Connection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobDescription.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/WhereIs.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/messages/TestChipLocationBean.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/messages/TestConnection.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/ReliabilityITCase.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/SpallocMachineTest.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TransceiverITCase.java
  SpiNNaker-comms/src/test/resources/spinn2.json
  SpiNNaker-comms/src/test/resources/spinn4.json
  SpiNNaker-machine/pom.xml
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/ChipLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Direction.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Router.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/VirtualMachine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/ChipBean.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/ChipDetails.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/ChipResources.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/MachineBean.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/MapperFactory.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/package-info.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestDirection.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestMachine.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestChipDetails.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestChipLocationBean.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestChipbean.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestMachineBean.java
  SpiNNaker-machine/src/test/resources/spinn2.json
  SpiNNaker-machine/src/test/resources/spinn4.json
  SpiNNaker-machine/src/test/resources/spinn4_fiddle.json
Labels: enhancement

#58 Javadoc hacking
  .travis.yml
  pom.xml
Labels: enhancement
