Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2020-02, with the labels that each got.

#254 Synchronisation added to prevent rare hang
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/OperationMapper.java
Labels: bug

#255 Tighter style for exceptions
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/selectors/RoundRobinConnectionSelector.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/AbstractIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/io/ChipMemoryIO.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/SystemVariableBootValues.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/AppID.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/DataType.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/RouterDiagnostics.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPRequestHeader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPResultMessage.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SDPHeader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SpinnakerRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/PropertyBasedDeserialiser.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocAPI.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/processes/FillProcess.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Functions.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/MemoryRegionCollection.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataReceiver.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Processor.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Router.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RoutingEntry.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/Tag.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/BufferManagerStorage.java
  src/support/checkstyle/style.xml
Labels: enhancement, minor

#261 Fewer timeouts
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/FastExecuteDataSpecification.java
Labels: enhancement

#263 Scamp for memory
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/FastExecuteDataSpecification.java
Labels: enhancement
