Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2021-07, with the labels that each got.

#347 Match data-spec changes for increase of max from 16 to 32
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Constants.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Functions.java
Labels: enhancement

#337 Publish maven packages
  .github/workflows/publish-pkgs.yml
  pom.xml
Labels: enhancement

#351 Spalloc server JSP interface
  SpiNNaker-allocserv/pom.xml
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/LocalAuthProviderImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/SQLQueries.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/SecurityConfig.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/ServiceConfig.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminControllerImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/UserControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/RootController.java
  SpiNNaker-allocserv/src/main/resources/application.yml
  SpiNNaker-allocserv/src/main/webapp/META-INF/public-web-resources/spalloc.css
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/adminfooter.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/basicfooter.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/board.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/createuser.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/erroroccurred.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/head.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/index.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/listusers.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/login.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/machine.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/main.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/password.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/userdetails.jsp
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/DbTest.java
  pom.xml
Labels: enhancement, spalloc server

#355 Create CITATION.cff
  .gitattributes
  CITATION.cff
Labels: enhancement, minor
