Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2021-03, with the labels that each got.

#279 Simplify recording
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/BufferedReceivingData.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/ChannelBufferState.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataReceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/RecordingRegion.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/RecordingRegionDataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/RecordingRegionsDescriptor.java
Labels: enhancement

#280 Make coveralls work again
  .github/workflows/build.yml
Labels: bug, critical, minor

#278 Try to prevent catastrophes from occurring
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
Labels: bug

#282 Create a security policy
  SECURITY.md
  pom.xml
Labels: critical, enhancement

#281 Don't collect boot receivers; we don't use them
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
Labels: bug, minor

#283 Move magic number into a private named constant
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/HostSendSequencedData.java
Labels: bug, minor

#284 Retry flood fill
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/FloodFillData.java
Labels: bug, minor
