Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2022-05, with the labels that each got.

#487 Fixes to logging
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/OperationMapper.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataReceiver.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/DatabaseEngine.java
Labels: bug

#482 Handle EIEIO proxying
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/SpallocProperties.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/model/IPAddress.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/ProxyCore.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/ProxyOp.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/ProxyUDPConnection.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/SpinWSHandler.java
  SpiNNaker-allocserv/src/main/resources/application.yml
Labels: enhancement, spalloc server

#493 Split the notification protocol out of the EIEIO protocol
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/NotificationConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/NotificationReceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/NotificationSender.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/EIEIOCommandID.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/eieio/EIEIOMessageFactory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/AbstractNotificationMessage.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/DatabaseConfirmation.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/NotificationMessage.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/NotificationMessageCode.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/PauseStop.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/StartResume.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/package-info.java
Labels: enhancement, minor

#494 Doc fix
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/Listenable.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/RouterDiagnostics.java
Labels: bug, blocker

#496 No P2PC command
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPCommand.java
Labels: bug

#497 Add Java 17 builds
  .github/workflows/build.yml
Labels: enhancement, minor

#488 Low level networking rework
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/BMPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/BootConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/ConnectionListener.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/DelegatingSCPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/EIEIOConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/IPAddressConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/NotificationConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/Listenable.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/model/MessageReceiver.java
Labels: enhancement

#489 Rework the timeout logic for fast connections
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataGatherer.java
Labels: bug

#501 Allow virtual chips outside of the size of a board
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
Labels: bug
