Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2022-09, with the labels that each got.

#570 Don't need to look UTF-8 by name ever
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/MockServer.java
Labels: bug, minor

#571 A few small fixes
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTask.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManagerTest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/CPUInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocJob.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/model/TestIptag.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/MockServer.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/spalloc/TestClient.java
Labels: bug, minor

#569 Proxied transceiver for Java spalloc client
  SpiNNaker-allocator/pom.xml
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ClientSession.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ClientUtils.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/JobDescription.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedBootConnection.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedEIEIOListenerConnection.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedSCPConnection.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedTransceiver.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxyProtocol.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxyProtocolClient.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/Session.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/SpallocClient.java
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/SpallocClientFactory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/BootConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/DelegatingSCPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/InetFactory.java
  pom.xml
Labels: enhancement

#574 Override Spring Boot on versioning of Jackson components
  pom.xml
Labels: bug, minor

#576 Fix the FIXME
  .github/workflows/build.yml
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/notification/AbstractNotificationMessage.java
  SpiNNaker-comms/src/main/resources/spalloc.ini
  SpiNNaker-py2json/src/main/python/spalloc_server/configuration.py
  SpiNNaker-py2json/src/main/python/spalloc_server/coordinates.py
  SpiNNaker-py2json/src/main/python/spalloc_server/links.py
  SpiNNaker-py2json/src/main/python/spinn_machine.py
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/DSEStorage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteDataSpecStorage.java
  pom.xml
Labels: bug, minor

#542 Removes code to do with Virtual Chips.
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/test/resources/spinn2.json
  SpiNNaker-comms/src/test/resources/spinn4.json
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/bean/ChipResources.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestChip.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestChipbean.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/bean/TestMachineBean.java
  SpiNNaker-machine/src/test/resources/h40w16.json
  SpiNNaker-machine/src/test/resources/spinn2.json
  SpiNNaker-machine/src/test/resources/spinn4.json
  SpiNNaker-machine/src/test/resources/spinn4_fiddle.json
  SpiNNaker-machine/src/test/resources/test24_12.json
  SpiNNaker-machine/src/test/resources/with_virtual.json
Labels: enhancement

#531 A different way to do short waits
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/GatherDownloadConnection.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/ThrottledConnection.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/WaitUtils.java
Labels: enhancement, minor

#596 Use the new log4j/slf4j connector
  SpiNNaker-allocator/pom.xml
  SpiNNaker-comms/pom.xml
  SpiNNaker-data-specification/pom.xml
  SpiNNaker-front-end/pom.xml
  SpiNNaker-machine/pom.xml
  SpiNNaker-storage/pom.xml
  keycloak-management-client/pom.xml
  pom.xml
Labels: bug, minor

#598 Add link to error prone docs
  pom.xml
Labels: minor

#581 Small changes
  SpiNNaker-allocator/pom.xml
  SpiNNaker-allocator/src/main/java/uk/ac/manchester/spinnaker/allocator/BoardCoords.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/TransceiverFactory.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Utils.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseCache.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/model/ConnectionInfo.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/ProxyCore.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/LocalAuthProviderImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/MachineResponse.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/MachinesResponse.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/admin/MDefLoaderTest.java
  SpiNNaker-comms/pom.xml
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/ConnectionListener.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/SystemVariableBootValues.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/Blacklist.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/Configuration.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/Connection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPCommandProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/MulticastRoutesControlProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/transceiver/TestTransceiver.java
  SpiNNaker-data-specification/pom.xml
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Functions.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/DataGatherer.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/RecordingRegionDataGatherer.java
  SpiNNaker-machine/pom.xml
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Chip.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/ChipLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/CoreLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/CoreSubsets.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Link.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Machine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/Processor.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/RegionLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/SpiNNakerTriadGeometry.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/VirtualMachine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/AbstractDataLink.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/FPGALinkData.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/FpgaId.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/InetIdTuple.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/datalinks/SpinnakerLinkData.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/IPTag.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/ReverseIPTag.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/Tag.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/datalinks/TestAbstractDataLink.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/datalinks/TestFpgaLinkData.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/datalinks/TestFpgaLinkId.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/datalinks/TestInetIdTuple.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/datalinks/TestSpinnakerLinkData.java
  SpiNNaker-py2json/src/test/java/uk/ac/manchester/spinnaker/py2json/TestConvert.java
  SpiNNaker-storage/pom.xml
  SpiNNaker-utils/src/test/java/uk/ac/manchester/spinnaker/utils/TestMappableIterable.java
  keycloak-management-client/pom.xml
Labels: minor

#599 Reduce duplicates in SpiNNaker-storage
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/Ordinals.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteBufferStorage.java
  SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteDataSpecStorage.java
Labels: minor

#600 Reduce duplicates relating to SpiNNaker-utils
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/Constants.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Utils.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseEngine.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/MachineDefaults.java
  SpiNNaker-machine/src/test/java/uk/ac/manchester/spinnaker/machine/TestProcessor.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/UnitConstants.java
Labels: minor

#601 Reduce duplicates: coordinate classes, phase 1
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/FirmwareLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/SpiNNaker1.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/SpiNNakerControl.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/bmp/MockTransceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/BMPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPReadMemory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPSetLED.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPWriteMemory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/EraseFlash.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/GetBMPVersion.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/GetFPGAResetStatus.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/InitFPGA.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadADC.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadCANStatus.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadFPGARegister.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadIPAddress.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadSerialFlash.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadSerialFlashCRC.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadSerialVector.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ResetFPGA.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/SetPower.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/UpdateFlash.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/WriteFPGAData.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/WriteFPGARegister.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/WriteFlashBuffer.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/WriteSerialFlash.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPReadMemoryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPReadSerialFlashProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPTransceiverInterface.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPWriteMemoryProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPWriteSerialFlashProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/UnimplementedBMPTransceiver.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/GeneralMessageTest.java
  SpiNNaker-machine/pom.xml
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/board/BMPBoard.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/board/package-info.java
  pom.xml
Labels: minor
