Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2022-11, with the labels that each got.

#633 Remove code that forced buffer copying
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPRequestPipeline.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPCommandProcess.java
Labels: bug, minor

#635 Update Spring Security because of CVE-2022-31692
  pom.xml
Labels: bug, blocker

#634 Move new spalloc client to SpiNNaker-comms
  SpiNNaker-allocator/pom.xml
  SpiNNaker-comms/pom.xml
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/AllocatedMachine.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/BoardCoords.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/BriefMachineDescription.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ClientSession.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ClientUtils.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/CreateJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/DeadLink.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/Direction.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/JobDescription.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/Jobs.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ListFetchingIter.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/Machines.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/Power.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedBootConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedEIEIOListenerConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedSCPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxiedTransceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxyProtocol.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/ProxyProtocolClient.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/RootInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/Session.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/SpallocClient.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/SpallocClientFactory.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/State.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/WhereIs.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/package-info.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/allocator/CommandLineCheck.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/allocator/JsonTest.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/allocator/ListFetchingIterTest.java
  pom.xml
Labels: minor

#641 Fix for failing tests
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/FastDataInProtocol.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/ByteBufferUtils.java
  SpiNNaker-utils/src/test/java/uk/ac/manchester/spinnaker/utils/TestByteBufferUtils.java
Labels: bug, blocker

#643 More javadoc links
  SpiNNaker-allocserv/pom.xml
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/ProxyCore.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/package-info.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/compat/JsonTest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/allocator/AllocatedMachine.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobDescription.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/JobState.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/messages/WhereIs.java
  pom.xml
Labels: bug, minor

#646 Link for javax.servlet.http
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/DirInfo.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/UserControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManager.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BlacklistStore.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/TaskException.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAwareBean.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseEngine.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/SpinWSHandler.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/AnyTypeMethodSecurityExpressionHandler.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/LocalAuthProviderImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/ControllerUtils.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/TestSupport.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/FirmwareLoaderTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManagerTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DBTestingUtils.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DbBasicTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/MemDBTestBase.java
  pom.xml
  src/support/javadoc/javax.validation/package-list
  src/support/javadoc/javax.ws.rs/package-list
  src/support/javadoc/org.keycloak.client/package-list
  src/support/javadoc/org.keycloak.core/package-list
Labels: bug, minor

#575 Login with bearer token
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/ClientSession.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/alloc/client/CommandLineCheck.java
Labels: enhancement, help wanted

#652 Fix for machine definition upload
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminController.java
Labels: bug, blocker

#654 Fixes to BMP mocking
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/FirmwareLoaderTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/bmp/BlacklistCommsTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/bmp/MockTransceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPTransceiverInterface.java
Labels: bug

#653 Some fixes for binding issues
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminControllerImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/model/UserRecord.java
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/admin/createuser.jsp
Labels: bug

#655 Return more details of the error to the user
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/BackgroundSupport.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/RequestFailedException.java
Labels: enhancement
