Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2023-03, with the labels that each got.

#751 Simple job test
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/alloc/client/CommandLineCheck.java
Labels: minor

#745 Tidy up now we use MySQL
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/UserControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/FirmwareLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/PhysicalSerialMapping.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseCache.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseEngineJDBCImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/SpinWSHandler.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/LocalAuthProviderImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/SecurityConfig.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/JobStateResponse.java
  SpiNNaker-allocserv/src/main/resources/queries/get_jobs_with_changes.sql
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DMLTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/web/StubJob.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/web/StubMachine.java
Labels: bug, minor, spalloc server

#752 Strip out some unused classes
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/ServiceConfig.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseCache.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseEngineJDBCImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/Row.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLiteFlags.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/TerminationNotifyingThreadFactory.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/UncheckedConnection.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/Utils.java
Labels: bug, minor

#754 Various minor fixes
  SpiNNaker-allocserv/pom.xml
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/SpallocProperties.java
  pom.xml
Labels: bug, minor

#753 Size of machine in compat mode is in chips
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/web/JsonTest.java
Labels: bug

#755 Fix logged errors in testing of compat code
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTask.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTest.java
Labels: bug, minor, spalloc server

#756 Some small doc fixes
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatService.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/Row.java
Labels: bug, minor

#760 Make some links secure
  .github/settings.xml
  SpiNNaker-allocserv/src/main/resources-filtered/swagger.properties
  SpiNNaker-comms/pom.xml
  SpiNNaker-data-specification/pom.xml
  SpiNNaker-front-end/pom.xml
  SpiNNaker-machine/pom.xml
  SpiNNaker-pacman/pom.xml
  SpiNNaker-storage/pom.xml
  SpiNNaker-utils/pom.xml
  pom.xml
Labels: minor

#763 Citation plus
  .github/dependabot.yml
  .github/workflows/build.yml
  CITATION.cff
Labels: enhancement, minor

#767 Mark a few more things as hidden in the docs
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DataAccessExceptionMapper.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLExceptionMapper.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/RequestFailedException.java
  SpiNNaker-data-specification/src/main/java/uk/ac/manchester/spinnaker/data_spec/Callable.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/CommandLineInterface.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/IPTag.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/tags/ReverseIPTag.java
Labels: minor
