Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2023-08, with the labels that each got.

#974 Fix an annoying error in Eclipse
  SpiNNaker-nmpiserv/pom.xml
Labels: bug, minor

#976 Bump checkstyle version to 10.12.2
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManager.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/proxy/SpinWSHandler.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/SecurityConfig.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/boot/SystemVariableBootValues.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SDPHeader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/SpallocConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/request/Gather.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/request/Placement.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/FastExecuteDataSpecification.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/OutputManagerImpl.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/machinemanager/SpallocMachineManagerImpl.java
  SpiNNaker-py2json/src/main/java/uk/ac/manchester/spinnaker/py2json/MachineDefinitionConverter.java
  pom.xml
Labels: minor

#967 Fix compat
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Command.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Utils.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/model/JobListEntryRecord.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
Labels: bug, enhancement

#995 Experimenting with how to handle epochs for better stability
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/TestSupport.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocCoreTest.java
Labels: bug, blocker

#994 Test reliability fixes
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/PowerController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManager.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Utils.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/TestSupport.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocCoreTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/bmp/BlacklistCommsTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DMLTest.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/ThreadUtils.java
Labels: bug, blocker

#742 Board Temperature Reading
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminControllerImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/AdminControllerSupport.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineStateControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/NonBootOperation.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/SpiNNaker1.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/SpiNNakerControl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/main/resources/spalloc-mysql.sql
  SpiNNaker-allocserv/src/main/resources/spalloc.sql
  SpiNNaker-allocserv/src/main/typescript/spinnaker.ts
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/admin/board.jsp
  SpiNNaker-allocserv/src/main/webapp/WEB-INF/views/admin/temperature.jsp
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DMLTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/ReadADC.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/ADCInfo.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/model/SerSupport.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/model/TestADCInfo.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/model/TestBlacklist.java
Labels: enhancement, spalloc server

#997 Add some missing doc comments
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManager.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/SystemController.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/DockerExecutorFactory.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/model/NMPILog.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/model/QueueJobCompat.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/rest/DockerAPI.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/rest/DockerCreateRequest.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/rest/DockerInspectResponse.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/rest/NMPIQueueCompat.java
Labels: bug, minor

#1010 Add dependency submission action
  .github/workflows/build.yml
Labels: minor

#1011 Joda Time classes appear in public API; enable linking in Javadoc
  pom.xml
Labels: minor

#1015 Do not fail when non-critical workflow steps fail
  .github/workflows/build.yml
Labels: bug, minor, blocker
