Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2023-07, with the labels that each got.

#796 Integration with NMPI Quota
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/SpallocProperties.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/admin/MachineDefinitionLoader.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/QuotaManager.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocAPI.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/SQLQueries.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/Job.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/JobResourceUpdate.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/NMPIv3API.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/Project.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/Quota.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/ResourceUsage.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/SessionRequest.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/SessionResourceUpdate.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/SessionResponse.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/nmpi/package-info.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/Grants.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/LocalAuthProviderImpl.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/OpenIDUserAware.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/Permit.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/SecurityConfig.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/security/TrustLevel.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/CreateJobRequest.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/SpallocServiceImpl.java
  SpiNNaker-allocserv/src/main/resources/spalloc-mysql.sql
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/allocator/SpallocCoreTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/compat/V1CompatTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DMLTest.java
  SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/CreateJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/CreateJob.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/spalloc/JobConstants.java
  mkpasswd.sh
Labels: enhancement, spalloc server

#938 We should only get jobs with the right permit
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
Labels: bug

#960 Update cff-validator version to v3
  .github/workflows/build.yml
Labels: minor, blocker

#959 Use right versioning scheme
  SpiNNaker-allocserv/pom.xml
  SpiNNaker-comms/pom.xml
  SpiNNaker-front-end/pom.xml
  SpiNNaker-machine/pom.xml
  SpiNNaker-pacman/pom.xml
  SpiNNaker-py2json/pom.xml
  SpiNNaker-storage/pom.xml
  SpiNNaker-utils/pom.xml
  keycloak-management-client/pom.xml
  pom.xml
Labels: bug, blocker
