Repository SpiNNakerManchester/JavaSpiNNaker, pull requests merged in 2023-09, with the labels that each got.

#1025 Unify thread utilities
  SpiNNaker-nmpiexec/pom.xml
  SpiNNaker-nmpiexec/src/main/java/uk/ac/manchester/spinnaker/nmpiexec/jobprocess/PyNNJobProcess.java
  SpiNNaker-nmpiexec/src/main/java/uk/ac/manchester/spinnaker/nmpiexec/utils/ThreadUtils.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/ThreadUtils.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/DockerExecutorFactory.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/JobManager.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/LocalJobExecuterFactory.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/OutputManagerImpl.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/jobmanager/XenVMExecuterFactory.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/machinemanager/FixedMachineManagerImpl.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/machinemanager/SpallocMachineManagerImpl.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/nmpi/NMPIQueueManagerCompat.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/nmpi/NMPIQueueManagerV3.java
  SpiNNaker-nmpiserv/src/main/java/uk/ac/manchester/spinnaker/nmpi/package-info.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/ThreadUtils.java
  SpiNNaker-utils/src/main/java/uk/ac/manchester/spinnaker/utils/UsedInJavadocOnly.java
Labels: minor

#1027 Bmp sanity
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/FirmwareLoader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/UDPConnection.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/bmp/BMPRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/model/VersionInfo.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/FECRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/ReinjectorRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/RouterTableRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/scp/SCPRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SDPHeader.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SDPLocation.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/messages/sdp/SpinnakerRequest.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPCommandProcess.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/BMPSendFailedException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/ProcessException.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
  SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/TxrxProcess.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/model/TestVersionInfo.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/GeneralMessageTest.java
  SpiNNaker-comms/src/test/java/uk/ac/manchester/spinnaker/messages/scp/TestVersion.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/download/GatherProtocolMessage.java
  SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/FastDataInProtocol.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/HasCoreLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/board/BMPLocation.java
  SpiNNaker-machine/src/main/java/uk/ac/manchester/spinnaker/machine/board/HasBMPLocation.java
Labels: bug

#1029 Make EpochMap safe against concurrent updates by the GC
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
Labels: bug

#992 Fix the notification of compat jobs
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/V1TaskImpl.java
Labels: bug

#1033 Add power off timestamp to power on boards on failure
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
Labels: bug

#1035 Retry proxy
  SpiNNaker-proxy/pom.xml
  SpiNNaker-proxy/src/main/java/uk/ac/manchester/spinnaker/proxy/TCPProxy.java
  SpiNNaker-proxy/src/main/java/uk/ac/manchester/spinnaker/proxy/package-info.java
  pom.xml
Labels: enhancement

#1057 Skip down services when building truststore
  SpiNNaker-allocserv/pom.xml
Labels: bug, blocker

#1037 Proxy tinkering
  SpiNNaker-proxy/pom.xml
  SpiNNaker-proxy/src/main/java/uk/ac/manchester/spinnaker/proxy/Remote.java
  SpiNNaker-proxy/src/main/java/uk/ac/manchester/spinnaker/proxy/TCPProxy.java
  SpiNNaker-proxy/src/main/resources/log4j2.xml
Labels: enhancement, minor

#1058 Bump versions on a couple of things
  pom.xml
Labels: minor

#1060 Remove unique constraint from blacklist_ops
  SpiNNaker-allocserv/src/main/resources/spalloc-mysql.sql
Labels: enhancement

#1066 Get the mod operator we want
  SpiNNaker-allocserv/src/main/resources/queries/connected_boards_at_coords.sql
Labels: bug

#1067 Fix the location
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
Labels: bug

#1073 Updates to dependabot configuration
  .github/dependabot.yml
Labels: blocker

#1084 Synchronize access to the database to avoid table deadlocks
  SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
Labels: bug

#1085 Dead links between allocated boards weren't being turned off
  SpiNNaker-allocserv/src/main/resources/queries/perimeter.sql
Labels: bug, blocker, spalloc server
